name:                lookupt
version:             0.1.0.0
github:              "nick-chandoke/lookupt"
license:             BSD3
author:              "Nicholas Chandoke"
maintainer:          "nicholas.chandoke@gmail.com"
copyright:           "2019 Nicholas Chandoke"

# Metadata used when publishing your package
# synopsis:
# category:

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Category of found and parsed objects

dependencies:
- base >= 4.7 && < 5
- containers
- directory
- transformers

library:
  source-dirs: src

tests:
  lookupt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lookupt

default-extensions:
- DataKinds
- DeriveFunctor
- FlexibleInstances
- MultiParamTypeClasses
- TypeFamilies
- KindSignatures
- LambdaCase
